server:
  port: 8200

eureka:
  instance:
    hostname: eureka8200.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone:  http://eureka8100.com:8100/eureka, http://eureka8300.com:8300/eureka
#  server:
#    enable-self-preservation: false
#    renewal-percent-threshold: 0.8

